author: ventureo
description: Random things I'm interested in
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-feed
relative_links:
  enabled: true
  collections: true
include:
  - README.md
